/* auto-generated by NAPI-RS */
/* eslint-disable */
/** RFC 8785 canonicalization utilities. All methods are static. */
export declare class AcdpCanonicalizer {
  /**
   * Canonicalize a JSON document to its RFC 8785 (JCS) form.
   *
   * * `jsonStr` — any JSON document as a string.
   *
   * Returns the canonical UTF-8 JSON string (sorted object keys, no
   * whitespace, `-0.0` normalized to `0`, ECMAScript number
   * formatting). Throws on malformed JSON, or if the document nests
   * past the canonicalizer's recursion ceiling.
   */
  static canonicalize(jsonStr: string): string
  /**
   * SHA-256 over the canonical (JCS) form of a JSON document, returned
   * as the ACDP envelope `"sha256:<64-lowercase-hex>"`.
   *
   * This is the hashing primitive behind `content_hash` /
   * `data_ref.content_hash`. It hashes the document *as given* — it
   * does NOT strip the RFC-ACDP-0001 §5.7 exclusion set, so to
   * recompute a body's `content_hash` the caller passes the already
   * producer-controlled object (or uses `AcdpVerifier.verifyContentHash`).
   */
  static contentHash(jsonStr: string): string
}

/** Stateless did:web string helpers. All methods are static. */
export declare class AcdpDid {
  /**
   * Translate a `did:web:…` DID to the HTTPS URL of its DID document
   * per RFC-ACDP-0001 §5.11.
   *
   * * `did:web:example.com` → `https://example.com/.well-known/did.json`
   * * `did:web:example.com:users:alice` → `https://example.com/users/alice/did.json`
   *
   * Throws with `.code === "not_did_web"` if the input is not a
   * `did:web` DID.
   */
  static webToUrl(did: string): string
  /**
   * Strip the `#fragment` from a DID URL, returning the bare DID.
   * Returns the input unchanged when it carries no fragment.
   */
  static stripFragment(didUrl: string): string
}

/**
 * A parsed did:web DID document. Construct with
 * [`AcdpDidDocument::parse`], then resolve a signing key with
 * [`AcdpDidDocument::key_for_algorithm`].
 */
export declare class AcdpDidDocument {
  /**
   * Parse a DID document and assert its `id` equals `expectedDid`.
   *
   * `expectedDid` is the bare DID being resolved (no fragment). The
   * `id`-match check (RFC-ACDP-0001 §9.1) stops a misconfigured or
   * hostile server from substituting another DID's keys.
   *
   * Throws `.code === "parse_failed"` on malformed JSON / missing
   * `id`, or `.code === "id_mismatch"` when `id` ≠ `expectedDid`.
   */
  static parse(jsonStr: string, expectedDid: string): AcdpDidDocument
  /** The DID this document describes. */
  get id(): string
  /**
   * Resolve a verification method to raw public-key bytes, enforcing
   * the full consumer-side gate:
   *
   * 1. the method `requestedKeyId` (matched by `#fragment`, exact —
   *    no loose suffix) must exist, else `.code === "key_not_found"`;
   * 2. it must be authorized in `assertionMethod`, else
   *    `.code === "key_not_authorized"`;
   * 3. any algorithm the method declares (via `type`, JWK params, or
   *    multibase multicodec prefix) must equal `requestedAlg`, else
   *    `.code === "alg_mismatch"` (downgrade defense, RFC-ACDP-0008
   *    §3.9);
   * 4. the key bytes must decode for `requestedAlg`, else
   *    `.code === "malformed_key"`.
   *
   * `requestedAlg` is `"ed25519"` or `"ecdsa-p256"`
   * (`.code === "unsupported_algorithm"` otherwise). `requestedKeyId`
   * is the full DID URL from the signature's `key_id`.
   */
  keyForAlgorithm(requestedKeyId: string, requestedAlg: string): ResolvedDidKey
  /**
   * Resolve a **registry receipt** signing key, applying the
   * RFC-ACDP-0010 §9 lifecycle instead of the `assertionMethod` gate:
   * retired receipt keys MUST remain in `verificationMethod`
   * indefinitely and MUST still verify historical receipts even after
   * rotation removes them from `assertionMethod`. A key absent from
   * `verificationMethod` entirely still fails
   * (`.code === "key_not_found"`) — full removal is the registry's
   * compromise-revocation signal.
   *
   * `historical` on the result is `true` when the key is no longer in
   * `assertionMethod`: verify the receipt, but report it with the
   * distinguishable *historically authorized* status. The
   * algorithm-downgrade defense (RFC-ACDP-0008 §3.9) and key decoding
   * are enforced identically to `keyForAlgorithm`.
   *
   * Use `keyForAlgorithm` for producer keys and auth challenges —
   * publish-time authorization still requires `assertionMethod`.
   */
  receiptKeyForAlgorithm(requestedKeyId: string, requestedAlg: string): ResolvedReceiptKey
}

/** RFC-ACDP-0012 §5 Merkle helpers. All methods are static. */
export declare class AcdpMerkle {
  /**
   * The §5.1 leaf hash of a transparency-log leaf:
   * `SHA-256(0x00 ‖ JCS(leaf))`, returned in the wire form
   * `"sha256:<64-hex>"`.
   *
   * * `leafJson` — the closed leaf object (e.g. the output of
   *   `AcdpVerifier.buildLogLeaf`). Shape-validated first; a
   *   malformed leaf throws (`.code === "invalid_log_proof"`)
   *   rather than hashing bytes no conformant log ever committed.
   */
  static leafHash(leafJson: string): string
  /**
   * The §5.1 interior-node hash `SHA-256(0x01 ‖ left ‖ right)` over
   * the raw digests the two wire-form (`"sha256:<hex>"`) arguments
   * encode. The 0x00/0x01 domain-separation prefixes are what stop
   * leaf/node second-preimage forgeries — never hash without them.
   */
  static nodeHash(leftHash: string, rightHash: string): string
  /**
   * The §5.2 RFC 6962 Merkle tree hash `MTH(D[n])` over an ordered
   * JSON array of wire-form leaf hashes (`'["sha256:...", ...]'`).
   * An empty array yields the empty-tree root, `SHA-256("")`.
   */
  static rootHash(leafHashesJson: string): string
}

/**
 * An ACDP producer signing with ECDSA-P256 (`ecdsa-p256`) instead of
 * the Ed25519 baseline.
 *
 * Mirrors [`AcdpProducer`] exactly — same JSON-in/JSON-out surface and
 * the same `PublishOpts` / `SupersedeOpts` shapes — but emits
 * `signature.algorithm = "ecdsa-p256"` and the IEEE 1363 `r‖s` wire
 * form. Use this when the producer's `did:web` verification method
 * declares a P-256 key. The DID document MUST declare the P-256
 * algorithm so consumers don't reject the signature on
 * algorithm-downgrade grounds (RFC-ACDP-0008 §3.9); use
 * [`AcdpP256Producer::did_verification_method`] to mint that entry.
 */
export declare class AcdpP256Producer {
  /** Generate a producer with a fresh random P-256 key (OsRng). */
  static generate(agentDid: string, keyId: string): AcdpP256Producer
  /**
   * Generate a producer whose identity **is** its fresh P-256 key
   * (`did:key`, ACDP 0.2). See [`AcdpProducer::generate_did_key`]
   * for the did:key rotation tradeoff.
   */
  static generateDidKey(): AcdpP256Producer
  /**
   * Construct a `did:key` producer from a 32-byte P-256 private
   * scalar (big-endian). Deterministic — the same seed always
   * derives the same `agentDid` / `keyId`. Throws if the bytes are
   * not exactly 32 or are not a valid scalar.
   */
  static fromSeedDidKey(seed: Buffer): AcdpP256Producer
  /**
   * Construct from a 32-byte P-256 private scalar (deterministic).
   * Throws if the bytes are not exactly 32 or are not a valid scalar.
   */
  static fromSeed(seed: Buffer, agentDid: string, keyId: string): AcdpP256Producer
  /** The producer's DID (`did:web:…` or `did:key:…`). */
  get agentDid(): string
  /**
   * The producer's signing-key DID URL (`did:web:…#key-1`, or the
   * `did:key:z…#z…` self-fragment form).
   */
  get keyId(): string
  /**
   * SEC1-uncompressed public key (`0x04 || x || y`, 65 bytes) as
   * standard base64. Use this to populate a did:web `JsonWebKey2020`
   * verification method.
   */
  get publicKeySec1B64(): string
  /**
   * The producer's P-256 public key as a JWK
   * (`{"kty":"EC","crv":"P-256","x":…,"y":…}`), returned as a JSON
   * object string. Drop this straight into a did:web `JsonWebKey2020`
   * verification method's `publicKeyJwk`.
   */
  get publicKeyJwk(): string
  /**
   * A complete `verificationMethod` entry (JSON object string) for a
   * did:web DID document, of type `JsonWebKey2020`.
   *
   * * `methodId` — the full DID URL for this key (e.g.
   *   `"did:web:agents.example.com:alice#key-1"`).
   * * `controller` — the bare DID that owns the key (no fragment).
   *
   * Consumers resolve the signature algorithm from this entry, so
   * publishing it is what keeps a P-256 signature from being rejected
   * on algorithm-downgrade grounds (RFC-ACDP-0008 §3.9).
   */
  didVerificationMethod(methodId: string, controller: string): string
  /**
   * The raw 32-byte private scalar, for storage in a key vault.
   * Returns a fresh `Buffer` each call — JS owns the bytes.
   */
  seedBytes(): Buffer
  /**
   * Build and sign a first-version PublishRequest. Returns the wire
   * JSON string. Same surface as [`AcdpProducer::build_publish_request`]
   * — including the explicit `acdp_version` default (the library's
   * current ACDP protocol version, `"0.2.0"` as of this release) and
   * the `acdpVersion` / `omitAcdpVersion` controls; only the
   * signature algorithm differs.
   */
  buildPublishRequest(opts: PublishOpts): string
  /**
   * Build and sign a supersession PublishRequest from a previous
   * version's `Body` JSON. Same semantics as
   * [`AcdpProducer::build_supersede_request`], including the
   * explicit `acdp_version` default (the library's current ACDP
   * protocol version, `"0.2.0"` as of this release).
   */
  buildSupersedeRequest(previousBodyJson: string, opts: SupersedeOpts): string
  /**
   * Sign a registry auth-challenge `signingInput` string with the
   * producer's P-256 key. Returns the base64 IEEE 1363 signature.
   */
  signChallenge(signingInput: string): string
}

/**
 * An ACDP producer: an Ed25519 signing key and its DID identity
 * (`did:web`, or `did:key` via the `*DidKey` factories — ACDP 0.2).
 *
 * All methods return wire-ready JSON strings the caller sends via its
 * own HTTP client. No HTTP calls are made inside this class.
 */
export declare class AcdpProducer {
  /** Generate a producer with a fresh random Ed25519 key (OsRng). */
  static generate(agentDid: string, keyId: string): AcdpProducer
  /**
   * Generate a producer whose identity **is** its fresh Ed25519 key
   * (`did:key`, ACDP 0.2). The `agentDid` and `keyId` are derived
   * from the public key — no domain, no DID-document hosting.
   * Consumers verify did:key contexts offline
   * (`AcdpVerifier.verifyBodyOffline`), with no dependency on the
   * producer's infrastructure remaining online.
   *
   * Tradeoff: did:key cannot rotate — a new key is a new identity,
   * and `supersedes` requires the same `agent_id`, so lineage
   * continuity ends with the key. Use `did:web` for long-lived
   * organizational anchors; use did:key for ephemeral or
   * archival-critical producers.
   */
  static generateDidKey(): AcdpProducer
  /**
   * Construct a `did:key` producer from a 32-byte Ed25519 seed.
   *
   * Deterministic — the same seed always derives the same
   * `agentDid` / `keyId`. The seed is the private key — protect it
   * as such. See [`AcdpProducer::generate_did_key`] for the did:key
   * rotation tradeoff.
   */
  static fromSeedDidKey(seed: Buffer): AcdpProducer
  /** Construct from a 32-byte Ed25519 seed (deterministic). */
  static fromSeed(seed: Buffer, agentDid: string, keyId: string): AcdpProducer
  /** The producer's DID (`did:web:…` or `did:key:…`). */
  get agentDid(): string
  /**
   * The producer's signing-key DID URL (`did:web:…#key-1`, or the
   * `did:key:z…#z…` self-fragment form).
   */
  get keyId(): string
  /**
   * Raw Ed25519 public key as standard base64 (44 chars with padding).
   * Use this to populate a did:web verification method.
   */
  get publicKeyB64(): string
  /**
   * The raw 32-byte seed, for storage in a key vault. Returns a
   * fresh `Buffer` each call — JS owns the bytes.
   */
  seedBytes(): Buffer
  /**
   * Build and sign a first-version PublishRequest. Returns the
   * wire JSON string.
   *
   * **By default (since 0.2) `acdp_version` is emitted explicitly,
   * set to the library's current ACDP protocol version
   * (`acdp::ACDP_VERSION` — `"0.2.0"` as of this release).** Pass
   * `omitAcdpVersion: true` to reproduce the 0.1.x omitted form (a
   * distinct JCS preimage, so a distinct `content_hash`), or
   * `acdpVersion` to pin another string.
   */
  buildPublishRequest(opts: PublishOpts): string
  /**
   * Build and sign a supersession PublishRequest from a previous
   * version's `Body` JSON. Version is propagated automatically
   * (`previous.version + 1`) and `lineage_id` is carried forward.
   *
   * **By default (since 0.2) `acdp_version` is emitted explicitly,
   * set to the library's current ACDP protocol version
   * (`acdp::ACDP_VERSION` — `"0.2.0"` as of this release)** — see
   * `buildPublishRequest`. Do not switch between the omitted and
   * explicit forms mid-lineage.
   */
  buildSupersedeRequest(previousBodyJson: string, opts: SupersedeOpts): string
  /**
   * Sign a registry auth-challenge `signingInput` string. Returns
   * the base64-encoded Ed25519 signature (88 chars with padding).
   * Used by the ACDP registry's bearer-token flow.
   */
  signChallenge(signingInput: string): string
}

/**
 * An SSRF policy: the synchronous classification half of the Rust
 * `SsrfPolicy`, exposed verdict-only (no DNS, no sockets).
 */
export declare class AcdpSsrfPolicy {
  /**
   * The production policy: HTTPS-only, IP literals rejected, every
   * private / loopback / link-local / IMDS / multicast / reserved
   * range forbidden.
   */
  static production(): AcdpSsrfPolicy
  /**
   * A test-only policy that additionally permits loopback
   * (`127.0.0.0/8` / `::1`) so a test harness can target a local
   * listener. Never use in production.
   */
  static allowTestLoopback(): AcdpSsrfPolicy
  /**
   * Validate a URL: scheme (HTTPS-only), IP-literal rejection, and —
   * for literal hosts — per-IP range filtering.
   *
   * Resolves on success. Throws an `Error` whose `.code` is the stable
   * reason on a policy violation.
   */
  checkUrl(url: string): void
  /**
   * Validate a single already-resolved IP address (IPv4 or IPv6
   * string). This is the per-address predicate the host loops over
   * after resolving DNS itself — rejecting the whole answer set if any
   * address fails (the mixed-answer rule stays in the host).
   *
   * Resolves on success. Throws with `.code === "invalid_ip"` if `ip`
   * is not a valid address, or with the stable range reason if it
   * falls in a forbidden range.
   */
  checkIp(ip: string): void
  /**
   * Validate that a redirect target stays within the origin's fetch
   * authority — identical scheme, host, and effective port (an
   * explicit `:443` equals the implicit https default).
   *
   * Resolves on success. Throws with `.code === "cross_authority"`
   * when the authority differs.
   */
  checkRedirectAuthority(fromUrl: string, toUrl: string): void
}

/** Consumer-side verification utilities. All methods are static. */
export declare class AcdpVerifier {
  /**
   * Verify that a body's `content_hash` matches the SHA-256 over
   * its JCS-canonicalized producer-controlled fields.
   *
   * * `bodyJson` — the `body` object from a `FullContext` retrieval
   *   (or the `PublishRequest` itself — both share the §5.7 layout).
   * * `expectedHash` — the `body.content_hash` string
   *   (`"sha256:<64-hex>"`).
   *
   * Returns `true` on success; throws on mismatch or bad JSON.
   */
  static verifyContentHash(bodyJson: string, expectedHash: string): boolean
  /**
   * Verify an Ed25519 signature over a `content_hash` string.
   *
   * The signing input per RFC-ACDP-0001 §5.8 is the ASCII bytes of
   * the full `"sha256:<hex>"` string — NOT the raw 32-byte digest.
   *
   * * `pubKeyB64` — standard base64 (padded) of the 32-byte raw
   *   Ed25519 public key (same shape as
   *   `AcdpProducer.publicKeyB64`).
   * * `sigB64` — the `body.signature.value` field from the wire
   *   format.
   * * `contentHash` — the `body.content_hash` string.
   *
   * Returns `true` on success; throws on failure.
   */
  static verifySignature(pubKeyB64: string, sigB64: string, contentHash: string): boolean
  /**
   * Verify an ECDSA-P256 signature over a `content_hash` string.
   *
   * The counterpart to `AcdpP256Producer` signing. The signing input
   * per RFC-ACDP-0001 §5.8 is the ASCII bytes of the full
   * `"sha256:<hex>"` string — NOT the raw 32-byte digest. The wire
   * signature is IEEE 1363 `r‖s` (64 bytes, base64), NOT DER.
   *
   * * `pubKeySec1B64` — standard base64 of the 65-byte
   *   SEC1-uncompressed public key (`0x04 || x || y`), the same shape
   *   as `AcdpP256Producer.publicKeySec1B64`.
   * * `sigB64` — the `body.signature.value` field from the wire
   *   format (88-char base64 of the 64-byte `r‖s`).
   * * `contentHash` — the `body.content_hash` string.
   *
   * Returns `true` on success; throws on failure.
   */
  static verifySignatureP256(pubKeySec1B64: string, sigB64: string, contentHash: string): boolean
  /**
   * Full offline verification of a retrieved `Body` from a `did:key`
   * producer (ACDP 0.2) — structural validation, `content_hash`
   * recomputation, key_id/agent_id binding, and signature check, all
   * with no network.
   *
   * * `bodyJson` — the `body` object from a `FullContext` retrieval
   *   (the registry-assigned fields must be present).
   *
   * Throws for `did:web` bodies — those need DID-document
   * resolution, which stays in JS land (resolve via `AcdpDid.webToUrl`
   * + `fetch`, then use `verifySignature`).
   *
   * Returns `true` on success; throws on any failure.
   */
  static verifyBodyOffline(bodyJson: string): boolean
  /**
   * Offline verification of a `PublishRequest` from a `did:key`
   * producer (ACDP 0.2): recomputes the `content_hash` over the
   * request's producer-controlled fields, then verifies the
   * signature against the key embedded in the `did:key` itself.
   *
   * * `requestJson` — the full PublishRequest wire JSON (e.g. the
   *   string `buildPublishRequest` returned).
   *
   * Throws for non-`did:key` requests — `did:web` verification needs
   * DID resolution, which stays in JS land by design.
   *
   * Returns `true` on success; throws on any failure.
   */
  static verifyPublishRequestOffline(requestJson: string): boolean
  /**
   * Diagnose a `content_hash` mismatch (ACDP 0.2 divergence
   * tooling). Probes the known cross-implementation divergence
   * patterns — `acdp_version` omitted vs explicit, null-vs-absent
   * optionals, sub-millisecond timestamps — and returns a
   * human-readable report naming the matching pattern (or the
   * recomputed hash and preimage when none matches).
   *
   * Never use this to *accept* a body; it is producer/SDK-author
   * tooling for chasing "the hash that won't reproduce".
   */
  static explainHashMismatch(bodyJson: string, expectedHash: string): string
  /**
   * The exact JCS canonical preimage hashed for `content_hash`,
   * returned as a UTF-8 string. When two SDKs disagree on a hash,
   * diffing their canonical preimages localizes the divergence in a
   * way two opaque digests never can.
   */
  static canonicalPreimage(bodyJson: string): string
  /**
   * SHA-256 fingerprint (`"sha256:<64-hex>"`) of a raw Ed25519
   * public key, as carried in a registry receipt's
   * `key_fingerprint` (ACDP 0.2).
   *
   * * `publicKeyB64` — standard base64 of the 32-byte raw key (the
   *   same shape as `AcdpProducer.publicKeyB64` /
   *   `ResolvedDidKey.publicKeyB64`).
   */
  static fingerprintEd25519B64(publicKeyB64: string): string
  /**
   * Verify a registry receipt (ACDP 0.2, RFC-ACDP-0010): the
   * canonical `created_at` byte-form check, the offline cross-checks
   * (`ctx_id`, recomputed body hash, producer key fingerprint,
   * ms-truncated `created_at`, `registry_did`/`origin_registry`
   * consistency), then the Ed25519 signature check against the
   * registry's receipt key — with the signature preimage hashed over
   * the **raw wire JSON** of the receipt as received (minus
   * `signature`), never a re-serialization of the parsed struct.
   *
   * Resolving `registry_did` to that key is the caller's job — DID
   * resolution stays in JS land by design (resolve the registry's
   * DID document via `AcdpDid.webToUrl` + `fetch`, extract the key
   * with `AcdpDidDocument.keyForAlgorithm`).
   *
   * **Two checks remain the HOST's obligation** — this binding makes
   * no HTTP calls and never sees the accompanying body:
   *
   * 1. **Serving-authority binding** — `receipt.registry_did` MUST
   *    equal `"did:web:" + <authority>` where `<authority>` is the
   *    authority the response was *actually fetched from*, not
   *    whatever the receipt claims.
   * 2. **Body bindings** — the receipt's `lineage_id`,
   *    `origin_registry`, and `created_at` MUST equal the
   *    accompanying body's fields, and the `recomputedBodyHash`
   *    argument MUST be independently recomputed from that body
   *    (run `AcdpVerifier.verifyContentHash` first) — never the
   *    body's echoed `content_hash` field.
   *
   * * `receiptJson` — the `registry_receipt` object from a
   *   `FullContext` retrieval.
   * * `registryPublicKeyB64` — standard base64 of the registry's
   *   32-byte raw Ed25519 receipt key.
   * * `expectedCtxId` — the ctx_id the caller actually requested.
   * * `recomputedBodyHash` — the *independently recomputed* body
   *   hash, never the body's echoed `content_hash` field.
   * * `producerKeyFingerprint` — fingerprint of the resolved
   *   producer key (see `fingerprintEd25519B64`).
   *
   * Returns `true` on success; throws with the failing check's
   * message otherwise.
   */
  static verifyReceipt(receiptJson: string, registryPublicKeyB64: string, expectedCtxId: string, recomputedBodyHash: string, producerKeyFingerprint: string): boolean
  /**
   * Verify a lineage-head receipt offline per RFC-ACDP-0011 §7:
   * closed parse, registry/lineage/head bindings, `as_of` clock
   * skew, and the registry signature over the RAW wire preimage —
   * against the registry key extracted from the caller-supplied DID
   * document (RFC-ACDP-0010 §9 receipt-key lifecycle: retired keys
   * verify with `historical: true`; fully removed keys fail closed).
   *
   * * `receiptJson` — the `lineage_head_receipt` object as received
   *   on the wire.
   * * `expectedJson` — the consumer's own expectations:
   *   `{"authority" and/or "registry_did", "lineage_id",
   *   "head_ctx_id", "head_version", "head_status",
   *   "on_current_endpoint"?}`. `authority` is the authority the
   *   response was *actually fetched from* (compare your HTTP
   *   client's URL, not any response field); `registry_did` is
   *   `capabilities.registry_did`; either derives the other.
   *   `on_current_endpoint` defaults to `true` (`GET /current` — §7
   *   step 5 byte-match); pass `false` for a full retrieval, where
   *   the §7 step 5b stale-consistency rule applies.
   * * `registryDidDocJson` — the registry's resolved DID document
   *   (resolution stays in JS land: `AcdpDid.webToUrl` + `fetch`).
   * * `nowRfc3339` — the consumer clock (defaults to now).
   * * `maxSkewSecs` — §7 step 6 allowance (default 120).
   * * `maxAgeSecs` — §6 freshness policy (default 300).
   *
   * Returns a JSON verdict: `{"valid": true, "stale": bool,
   * "age_secs": int, "historical": bool}` — staleness is policy,
   * not verification failure — or `{"valid": false, "code":
   * "invalid_receipt"|..., "error": ...}`. Throws only on malformed
   * host input.
   */
  static verifyLineageHeadReceipt(receiptJson: string, expectedJson: string, registryDidDocJson: string, nowRfc3339?: string | undefined | null, maxSkewSecs?: number | undefined | null, maxAgeSecs?: number | undefined | null): string
  /**
   * Verify a transparency-log checkpoint (signed tree head) offline
   * per RFC-ACDP-0012 §9.3: closed parse, optional `logId` pin
   * (§7.4 — a new `log_id` is an explicit history reset), timestamp
   * form + clock skew, and the registry signature over the RAW wire
   * preimage against the receipt key from the caller-supplied DID
   * document (retired keys verify with `historical: true`).
   *
   * The HOST still owns the §9.3 step 3 serving-authority half:
   * confirm the `log_id`'s registry DID matches the authority the
   * checkpoint was actually fetched from and
   * `capabilities.registry_did`.
   *
   * Returns `{"valid": true, "log_id", "tree_size", "root_hash",
   * "age_secs", "historical"}` (retain `tree_size`/`root_hash` for
   * future §9.2 consistency checks) or `{"valid": false, "code":
   * "invalid_log_proof", "error": ...}`.
   */
  static verifyLogCheckpoint(checkpointJson: string, registryDidDocJson: string, expectedLogId?: string | undefined | null, nowRfc3339?: string | undefined | null, maxSkewSecs?: number | undefined | null): string
  /**
   * Verify a transparency-log inclusion proof offline —
   * RFC-ACDP-0012 §9.1 steps 2 and 4–6: hash the RECONSTRUCTED
   * leaf, check the proof ↔ checkpoint bindings, fold the audit
   * path, compare against the checkpoint root.
   *
   * * `inclusionJson` — the proof (`log_id`, `leaf_index`,
   *   `tree_size`, `inclusion_path`, optionally an embedded
   *   `log_checkpoint`).
   * * `checkpointJson` — the checkpoint the proof verifies against.
   *   Inserted when the proof carries none; when the proof embeds
   *   one, the two MUST be byte-equal (a proof quietly carrying a
   *   different checkpoint is the substitution §9.1 step 3 exists
   *   to stop). Verify its signature separately with
   *   `verifyLogCheckpoint` — the verdicts are independent.
   * * `reconstructedLeafJson` — the leaf built from *verified* body
   *   + receipt material via `buildLogLeaf` (§9.1 step 1). NEVER
   *   pass a leaf echoed by the registry — the whole point is that
   *   the verifier vouches for the leaf bytes itself.
   *
   * Returns `{"valid": true, "leaf_hash": "sha256:..."}` or
   * `{"valid": false, "code": "invalid_log_proof", "error": ...}`.
   */
  static verifyLogInclusion(inclusionJson: string, checkpointJson: string, reconstructedLeafJson: string): string
  /**
   * Verify a transparency-log consistency proof offline —
   * RFC-ACDP-0012 §9.2, the history-rewrite detector: prove the
   * tree the verifier RETAINED a root for (`firstRootHash`, at
   * `first_tree_size`) is a prefix of the checkpointed later tree.
   *
   * * `consistencyJson` — the proof (`log_id`, `first_tree_size`,
   *   `second_tree_size`, `consistency_path`, optionally an
   *   embedded `log_checkpoint`).
   * * `checkpointJson` — the later checkpoint (merged/byte-checked
   *   exactly as in `verifyLogInclusion`; verify its signature
   *   separately with `verifyLogCheckpoint`).
   * * `firstRootHash` — the verifier's own retained root
   *   (`"sha256:<hex>"`) — retaining it is the whole point.
   *
   * Returns `{"valid": true}` or `{"valid": false, "code":
   * "invalid_log_proof", "error": ...}`. A fold failure between two
   * signature-valid checkpoints of one `log_id` is cryptographic
   * evidence of a logged-history rewrite — retain both checkpoints
   * and the failing path (§9.2, §15).
   */
  static verifyLogConsistency(consistencyJson: string, checkpointJson: string, firstRootHash: string): string
  /**
   * Build the canonical RFC-ACDP-0012 §4 log leaf from a VERIFIED
   * RFC-ACDP-0010 receipt (§9.1 step 1) — every leaf field other
   * than `receipt_hash` duplicates a receipt field, and
   * `receipt_hash` is the receipt's §5 preimage hash, computed here
   * over the RAW wire JSON as received. Returns the leaf as a JSON
   * string, ready for `verifyLogInclusion` / `AcdpMerkle.leafHash`.
   *
   * Run `verifyReceipt` on the receipt FIRST: a leaf reconstructed
   * from an unverified receipt proves membership of a claim nobody
   * has checked. Throws on a malformed receipt
   * (`.code === "invalid_receipt"`).
   */
  static buildLogLeaf(receiptJson: string): string
  /**
   * Verify one `registry_state.lifecycle_events` entry offline per
   * RFC-ACDP-0013 §5: closed §4 parse, binding to `expectedCtxId`
   * (a signed event cannot be replayed against another context),
   * the §5 actor binding (`signature.key_id` DID = `actor`), and
   * the signature over the RAW wire preimage.
   *
   * * `eventJson` — the event object as received.
   * * `actorDidDocJson` — the ACTOR's resolved DID document, or
   *   `null` for a `did:key` actor (self-certifying — verified
   *   natively with no document). For `did:web` actors the key must
   *   pass the `assertionMethod` gate, like a body signature.
   * * `expectedCtxId` — the ctx_id of the context whose registry
   *   state carries the event.
   *
   * The HOST still owns the §4/§12 authorization check that `actor`
   * equals the context's `body.agent_id` (producer-initiated) or
   * the registry's `capabilities.registry_did` (registry-initiated)
   * — this binding sees neither document. Retraction state itself
   * is derived from array order, last `retracted`/`republished`
   * event wins; unknown event types are inert (§7.1, §7.3).
   *
   * Returns `{"valid": true, "event_id", "event_type", "actor"}` or
   * `{"valid": false, "code": ..., "error": ...}` (an unsigned
   * event fails — producer-initiated events MUST be signed).
   */
  static verifyLifecycleEvent(eventJson: string, actorDidDocJson: string | undefined | null, expectedCtxId: string): string
  /**
   * Parse and shape-validate a `key-revocation` context body
   * (RFC-ACDP-0014 §4) and derive its §5/§6 trust class. Returns
   * the typed revocation as JSON: `{"revoked_key_fingerprint",
   * "compromised_since", "reason"?, "revoked_key_id"?,
   * "revoked_key_controller", "publisher", "trust_class":
   * "producer_signed"|"registry_attested"}`. The fingerprint is
   * authoritative; `compromised_since` is the compromise boundary
   * T. Never collapse the two trust classes when reporting (§6).
   *
   * * `bodyJson` — the retrieved context `body` (the §5.7 layout
   *   including registry-assigned fields).
   * * `signerFingerprint` — the RFC-ACDP-0010 §6 fingerprint of the
   *   RESOLVED key that signed the body, for the §5 step 2
   *   not-self-signed rule. For `did:key` signers the check runs
   *   natively from the body itself; for `did:web` signers resolve
   *   the key in JS land (`AcdpDidDocument.keyForAlgorithm` +
   *   `fingerprintEd25519B64`) and pass its fingerprint here — a
   *   revocation signed by the very key it revokes proves only
   *   possession of the attacker-held key and throws
   *   (`.code === "key_not_authorized"`).
   *
   * Parsing does NOT verify the body: run the ordinary hash +
   * signature pipeline (`verifyContentHash` + `verifySignature`, or
   * `verifyBodyOffline` for did:key) before trusting the result.
   * Throws with `.code === "schema_violation"` on §4 shape
   * violations.
   */
  static parseKeyRevocation(bodyJson: string, signerFingerprint?: string | undefined | null): string
  /**
   * Apply the RFC-ACDP-0014 §7 compromise-boundary rule — the
   * fail-closed classification the Rust client uses, over the
   * earliest `compromised_since` among the supplied revocations
   * naming the key (§4 monotonicity: a superseding revocation can
   * widen, never quietly shrink, the window — feed the whole
   * lineage through, superseded revocations included).
   *
   * * `revocationsJson` — JSON array of VERIFIED revocations (the
   *   shapes `parseKeyRevocation` returns). Which trust classes to
   *   act on is the caller's §6 policy.
   * * `signerFingerprint` — fingerprint of the key that signed the
   *   context under verification.
   * * `receiptCreatedAtRfc3339` — `created_at` from a registry
   *   receipt VERIFIED per RFC-ACDP-0010 §8, or `null` when there
   *   is no verified receipt. NEVER the bare body `created_at` — it
   *   is registry-assigned, producer-unsigned, and
   *   attacker-backdatable (§7 step 1).
   *
   * Returns `{"authorization": "none"}` (no revocation names the
   * key — ordinary rules apply), `{"authorization":
   * "historically_authorized_pre_compromise", "boundary": ...}` (§7
   * step 2 — still verify the signature itself, under the
   * RFC-ACDP-0010 §10 historical rule), or `{"authorization":
   * "none", "boundary": ..., "error": ...}` — fail closed (§7
   * steps 3–4).
   */
  static classifyUnderRevocation(revocationsJson: string, signerFingerprint: string, receiptCreatedAtRfc3339?: string | undefined | null): string
  /**
   * Mint a signed transparency-log witness cosignature
   * (RFC-ACDP-0015 §5) — the MINT surface a host-language witness
   * service uses. The witness observes a checkpoint and cosigns it
   * with its OWN Ed25519 key (a witness key, distinct from the
   * registry receipt key); the returned `log_cosignature` uses the
   * RFC-ACDP-0010 §5 construction verbatim (the witness signs the
   * ASCII bytes of the `"sha256:<hex>"` cosignature-hash string).
   *
   * * `witnessedCheckpointJson` — the identity-bearing subset of the
   *   checkpoint the witness observed: `{"log_id", "tree_size",
   *   "root_hash", "timestamp"}` (closed schema).
   * * `witnessDid` — the witness's own DID (`did:web` or `did:key`).
   *   The signing-key DID URL is derived as
   *   `"<witnessDid>#witness-key-1"` (the §5/§9 witness-key
   *   convention).
   * * `witnessSeedHex` — the witness Ed25519 signing seed, hex-
   *   encoded (64 hex chars → 32 bytes). The same seed produces
   *   byte-identical cosignatures across bindings.
   * * `witnessedAtRfc3339` — the witness-clock observation time
   *   (canonical millisecond RFC 3339 UTC; truncated to ms).
   *
   * Returns the signed `log_cosignature` as a JSON string. This is
   * the RAW mint (no §7 obligation — the checkpoint's own signature
   * and consistency against a retained head are the host's job).
   * Throws on malformed input (bad seed / timestamp / witness DID /
   * witnessed_checkpoint).
   */
  static buildWitnessCosignature(witnessedCheckpointJson: string, witnessDid: string, witnessSeedHex: string, witnessedAtRfc3339: string): string
  /**
   * Verify one witness cosignature against a checkpoint the consumer
   * has itself verified, offline per RFC-ACDP-0015 §8 (steps 1–5):
   * closed parse + witness binding, checkpoint binding, the witness
   * signature over the RAW wire preimage against the key resolved
   * from the caller-supplied witness DID document (§9: looked up in
   * `verificationMethod`, retired keys stay verifiable), and the
   * `witnessed_at` well-formedness + forward-skew check.
   *
   * * `cosigJson` — the `log_cosignature` object as received.
   * * `witnessDidDocJson` — the WITNESS's resolved DID document
   *   (resolution stays in JS land). Its `id` MUST equal the
   *   cosignature's `witness_id`.
   * * `expectedCheckpointJson` — the RFC-ACDP-0012 checkpoint the
   *   consumer independently holds and verified; the cosignature's
   *   `{log_id, tree_size, root_hash}` MUST match it (§8 step 4).
   * * `nowRfc3339` — the consumer clock (defaults to now).
   * * `maxClockSkewSecs` — §8 step 5 forward allowance (default 120).
   *
   * Returns a JSON verdict: `{"valid": true, "witness_id": ...,
   * "age_secs": int, "stale": bool}` — staleness (§8.1) is policy,
   * not a verification failure — or `{"valid": false, "code":
   * "invalid_witness_cosignature"|..., "error": ...}`. Throws only
   * on malformed host input.
   */
  static verifyWitnessCosignature(cosigJson: string, witnessDidDocJson: string, expectedCheckpointJson: string, nowRfc3339?: string | undefined | null, maxClockSkewSecs?: number | undefined | null): string
  /**
   * Compute the RFC-ACDP-0015 §8 N-witnessed report over a set of
   * cosignatures for a checkpoint the consumer has itself verified.
   * A cosignature counts toward N iff it names a TRUSTED witness,
   * covers the checkpoint's `(log_id, tree_size, root_hash)` tuple,
   * and passes every §8 step; DISTINCT `witness_id` values are
   * counted. A cosignature that fails a step does not fail the
   * checkpoint — it is recorded in `failures` and simply does not
   * count.
   *
   * * `cosignaturesJson` — a JSON array of `log_cosignature` objects.
   * * `expectedCheckpointJson` — the verified checkpoint the quorum
   *   is over.
   * * `trustedWitnessDidsJson` — a JSON array of the witness DIDs the
   *   consumer trusts; only these can count.
   * * `witnessDidDocsJson` — a JSON object mapping each `witness_id`
   *   to its resolved DID document.
   * * `policyJson` — `{"min_witnesses"?, "max_age_secs"?,
   *   "max_clock_skew_secs"?}`. Defaults mirror the Rust
   *   `WitnessPolicy`: `min_witnesses=1`, `max_age_secs=300` (an
   *   explicit `null` disables the freshness split),
   *   `max_clock_skew_secs=120`.
   * * `nowRfc3339` — the consumer clock (defaults to now).
   *
   * Returns a JSON report: `{"witnessed_count", "witnesses",
   * "meets_quorum", "fresh_witnessed_count", "meets_fresh_quorum",
   * "failures"}`. Throws on malformed host input.
   */
  static evaluateWitnessQuorum(cosignaturesJson: string, expectedCheckpointJson: string, trustedWitnessDidsJson: string, witnessDidDocsJson: string, policyJson: string, nowRfc3339?: string | undefined | null): string
}

/**
 * Options for `buildPublishRequest`. Field names map directly to the
 * PublishRequest wire schema (camelCase on the JS side).
 */
export interface PublishOpts {
  /** Human-readable title (1..=500 chars). */
  title: string
  /** Closed enum or namespaced custom (`^[a-z][a-z0-9_]*:[a-z][a-z0-9_-]*$`). */
  contextType: string
  /** `public` | `restricted` | `private`. Defaults to `public`. */
  visibility?: string
  /** Long human-readable description (≤ 5000 chars). */
  description?: string
  /**
   * Producer-supplied summary for search results (≤ 1000 chars).
   * Part of ProducerContent — included in the content_hash preimage.
   */
  summary?: string
  /** Free-form tags (each: `^[A-Za-z0-9][A-Za-z0-9_.-]*$`, ≤ 100 chars). */
  tags?: Array<string>
  /** Subject-domain identifier (≤ 200 chars). */
  domain?: string
  /**
   * Producer-specific structured metadata. MUST be a JSON-encoded
   * object string (it is re-parsed so it lands as a JSON object,
   * not a quoted string).
   */
  metadata?: string
  /**
   * Lineage of contexts this body was derived from (`acdp://…` ids,
   * ≤ 1000 unique).
   */
  derivedFrom?: Array<string>
  /** Audience DIDs — required (≥ 1) when `visibility = "restricted"`. */
  audience?: Array<string>
  /** Optional JSON Schema URI describing the metadata shape. */
  schemaUri?: string
  /** Contributors (DIDs, ≤ 100 unique). */
  contributors?: Array<string>
  /**
   * Data references — a JSON-encoded array of `acdp-data-ref` objects.
   * Part of ProducerContent, so it is included in the content_hash
   * preimage.
   */
  dataRefs?: string
  /**
   * External anchors (RFC-ACDP-0016) — a JSON-encoded array of
   * `{scheme, content_hash, uri?}` objects. Part of ProducerContent,
   * so it is included in the content_hash preimage.
   */
  anchors?: string
  /**
   * RFC 3339 timestamp after which the conclusions should no longer be
   * relied upon. Truncated to millisecond precision.
   */
  expiresAt?: string
  /**
   * Time window the data covers — a JSON object
   * `{"start": <rfc3339>, "end": <rfc3339>}`. Both ends truncated to
   * millisecond precision.
   */
  dataPeriod?: string
  /**
   * Self-verifying `lin:sha256:<hex>` lineage id. v2+ supersession
   * only — rejected on first-version publishes.
   */
  expectedLineageId?: string
  /**
   * Explicit `acdp_version` string for the emitted request.
   *
   * **SDK default (since 0.2): `acdp_version` is emitted explicitly,
   * set to the library's current ACDP protocol version
   * (`acdp::ACDP_VERSION` — `"0.2.0"` as of this release).** Per
   * RFC-ACDP-0001 §6 consumers treat an absent field as `"0.1.0"`,
   * but the omitted and explicit forms are *different JCS preimages*
   * and therefore hash differently — pick one form per lineage and
   * never switch mid-lineage.
   */
  acdpVersion?: string
  /**
   * When `true`, omit `acdp_version` entirely (the 0.1.x SDK default
   * form). Use this only to reproduce hashes signed under the
   * omitted form (e.g. the sig-001 golden vector); takes precedence
   * over `acdpVersion`.
   */
  omitAcdpVersion?: boolean
}

/**
 * A verification method resolved to raw public-key bytes, in the
 * base64 shape the host's pinned-key directory speaks.
 */
export interface ResolvedDidKey {
  /** Verification-method id (full DID URL with `#fragment`). */
  keyId: string
  /** `ed25519` or `ecdsa-p256`. */
  algorithm: string
  /**
   * Standard base64 of the raw key bytes:
   * * ed25519 — 32 bytes
   * * ecdsa-p256 — 65-byte SEC1 uncompressed (`0x04 || x || y`)
   */
  publicKeyB64: string
}

/**
 * [`ResolvedDidKey`] plus the RFC-ACDP-0010 §9 lifecycle signal for
 * registry receipt keys.
 */
export interface ResolvedReceiptKey {
  /** Verification-method id (full DID URL with `#fragment`). */
  keyId: string
  /** `ed25519` or `ecdsa-p256`. */
  algorithm: string
  /** Standard base64 of the raw key bytes (see [`ResolvedDidKey`]). */
  publicKeyB64: string
  /**
   * `true` when the key is retained in `verificationMethod` but no
   * longer referenced by `assertionMethod` — a retired receipt key.
   * Verify the receipt, but report it with the distinguishable
   * *historically authorized* status (RFC-ACDP-0010 §9).
   */
  historical: boolean
}

/**
 * Options for `buildSupersedeRequest`. Any field omitted is carried
 * over from `previousBodyJson` unchanged (mirrors `new_version_from`).
 */
export interface SupersedeOpts {
  title?: string
  summary?: string
  description?: string
  tags?: Array<string>
  domain?: string
  metadata?: string
  /**
   * JSON-encoded array of `acdp-data-ref` objects (replaces the
   * carried-over data refs when present).
   */
  dataRefs?: string
  /**
   * JSON-encoded array of `{scheme, content_hash, uri?}` anchor
   * objects (RFC-ACDP-0016; replaces the carried-over anchors when
   * present).
   */
  anchors?: string
  /**
   * Unset `anchors` entirely (the only way to produce a version with
   * none, since omitting `anchors` carries the previous version's
   * value forward and `anchors: "[]"` is rejected by the
   * absent-when-empty rule). Takes precedence over `anchors`,
   * mirroring `omitAcdpVersion`'s precedence over `acdpVersion`.
   */
  clearAnchors?: boolean
  /** RFC 3339 expiry timestamp. */
  expiresAt?: string
  /** JSON object `{"start": <rfc3339>, "end": <rfc3339>}`. */
  dataPeriod?: string
  /** Self-verifying `lin:sha256:<hex>` lineage id (v2+). */
  expectedLineageId?: string
  /**
   * Explicit `acdp_version` string. **By default (since 0.2) the
   * library's current ACDP protocol version (`acdp::ACDP_VERSION` —
   * `"0.2.0"` as of this release) is emitted explicitly** — see
   * `PublishOpts.acdpVersion`. Do not switch the form mid-lineage.
   */
  acdpVersion?: string
  /**
   * When `true`, omit `acdp_version` entirely (the 0.1.x form);
   * takes precedence over `acdpVersion`.
   */
  omitAcdpVersion?: boolean
}
